#!/usr/bin/env python3
"""TR-1um_STDCELL.gds を読んで、セルの実寸法 / Tr数 / ピンを表にし、
Yosys 用 genlib と area_estimate.py 用の面積テーブルを生成する。

  usage: python3 scripts/cellinfo.py lef/TR-1um_STDCELL.gds [--genlib out.genlib] [--check]

レイヤ規約（GDS から読み取ったもの）:
  (3,1)=P+ implant  (3,2)=N+ implant  (8,1)=poly/GC  (11,0)=contact
  (13,0)=M1  (19,0)=V1  (20,0)=M2  (48,1)=電源レール/内部ネットラベル
  (49,1)=信号ピン(M2上のマーカ)  (140,0)=N-well  (235,0)=セル境界(abutment box)
セル面積 = (235,0) の外形。行高 64.8 µm、ポリピッチ 5.4 µm、セル幅 = 10.8 + n*5.4。
"""
from __future__ import annotations
import argparse, sys

try:
    import gdstk
except ImportError:
    sys.exit("pip install gdstk --break-system-packages")

ROW_H, POLY_PITCH, W_BASE = 64.8, 5.4, 10.8
L_BOUND, L_NWELL, L_POLY, L_PIN, L_LBL = (235, 0), (140, 0), (8, 1), (49, 1), (48, 1)
L_PIMP, L_NIMP = (3, 1), (3, 2)


def sel(cell, ld):
    return [p for p in cell.polygons if (p.layer, p.datatype) == ld]


def devices(cell):
    """poly ∩ (implant ∩/∖ nwell) で実ゲートを取り出す。戻り値 {'P':[W..],'N':[W..]}"""
    poly, nwell = sel(cell, L_POLY), sel(cell, L_NWELL)
    out = {}
    for tag, ld, op in (("P", L_PIMP, "and"), ("N", L_NIMP, "not")):
        act = gdstk.boolean(sel(cell, ld), nwell, op, precision=1e-3)
        gates = gdstk.boolean(poly, act, "and", precision=1e-3)
        out[tag] = [round(float(g.points[:, 1].max() - g.points[:, 1].min()), 2) for g in gates]
    return out


def scan(path):
    lib = gdstk.read_gds(path)
    rows = []
    for cell in sorted(lib.cells, key=lambda c: c.name):
        b = sel(cell, L_BOUND)
        if not b:
            continue
        pts = b[0].points
        w = round(float(pts[:, 0].max() - pts[:, 0].min()), 3)
        h = round(float(pts[:, 1].max() - pts[:, 1].min()), 3)
        d = devices(cell)
        rows.append(dict(
            name=cell.name, w=w, h=h, area=round(w * h, 1),
            nP=len(d["P"]), nN=len(d["N"]), tr=len(d["P"]) + len(d["N"]),
            WP=sorted(set(d["P"])), WN=sorted(set(d["N"])),
            pins=[l.text for l in cell.labels if l.layer == L_PIN[0]],
            pinshapes=len(sel(cell, L_PIN)),
            netlabels=sorted({l.text for l in cell.labels if l.layer == L_LBL[0]}),
        ))
    return rows


def check(rows):
    """設計規約からの逸脱を洗い出す"""
    bad = []
    for r in rows:
        k = (r["w"] - W_BASE) / POLY_PITCH
        if abs(k - round(k)) > 1e-6:
            bad.append(f"{r['name']}: 幅 {r['w']} µm がポリピッチ格子外 "
                       f"(10.8 + {k:.3f}×5.4 / 最寄り {W_BASE + round(k)*POLY_PITCH:.1f})")
        if abs(r["h"] - ROW_H) > 1e-6:
            bad.append(f"{r['name']}: 行高 {r['h']} µm (規定 {ROW_H})")
        if r["tr"] and r["pinshapes"] == 0:
            bad.append(f"{r['name']}: (49,1) のピン形状が無い（ラベルのみ）")
        sig = [n for n in r["netlabels"] if n not in ("vdd", "gnd")]
        outside = [n for n in sig if n.isupper() and n not in ("CKP", "CKB", "QM", "QS")]
        if outside:
            bad.append(f"{r['name']}: {','.join(outside)} が (48,1) にある"
                       f"（外部ピンなら他セル同様 (49,1) へ）")
    return bad


# --- genlib 用の論理式（面積は GDS 実測で埋める）---
FUNC = [
    ("INV_X1",  "Y=!A;",            "INV"),
    ("BUF_X1",  "Y=A;",             "NONINV"),
    ("NAND2",   "Y=!(A*B);",        "INV"),
    ("NAND3",   "Y=!(A*B*C);",      "INV"),
    ("NAND4",   "Y=!(A*B*C*D);",    "INV"),
    ("NOR2",    "Y=!(A+B);",        "INV"),
    ("NOR3",    "Y=!(A+B+C);",      "INV"),
    ("NOR4",    "Y=!(A+B+C+D);",    "INV"),
    ("AND2_X1", "Y=A*B;",           "NONINV"),
    ("AND3_X1", "Y=A*B*C;",         "NONINV"),
    ("AND4_X1", "Y=A*B*C*D;",       "NONINV"),
    ("OR2",     "Y=A+B;",           "NONINV"),
    ("OR3",     "Y=A+B+C;",         "NONINV"),
    ("OR4",     "Y=A+B+C+D;",       "NONINV"),
    ("XOR2",    "Y=(A*!B)+(!A*B);", "UNKNOWN"),
    ("XNOR2",   "Y=(A*B)+(!A*!B);", "UNKNOWN"),
    ("MUX2",    "Y=(A*S)+(B*!S);",  "UNKNOWN"),
]


def genlib(rows):
    a = {r["name"]: r["area"] for r in rows}
    out = [f"# TR-1um STDCELL - area from GDS (235,0) abutment box [um^2], row height {ROW_H}um",
           "# generated by scripts/cellinfo.py   (delays are placeholders)",
           "GATE ZERO   0.0    Y=CONST0;",
           "GATE ONE    0.0    Y=CONST1;"]
    for name, fn, ph in FUNC:
        if name not in a:
            continue
        out.append(f"GATE {name:<9}{a[name]:>8.1f} {fn:<20}PIN * {ph:<8}1 999 1 0.2 1 0.2")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("gds")
    ap.add_argument("--genlib")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rows = scan(args.gds)
    print(f"{'cell':<12}{'W':>8}{'H':>7}{'area':>10}{'Tr':>4}  {'W(P)':<14}{'W(N)':<7} pins")
    for r in rows:
        wp = "/".join(f"{v:g}" for v in r["WP"]) or "-"
        wn = "/".join(f"{v:g}" for v in r["WN"]) or "-"
        print(f"{r['name']:<12}{r['w']:>8.1f}{r['h']:>7.1f}{r['area']:>10.1f}{r['tr']:>4}  "
              f"{wp:<14}{wn:<7} {','.join(dict.fromkeys(r['pins']))}")

    if args.check:
        bad = check(rows)
        print("\n=== 規約チェック ===")
        print("\n".join("  ! " + b for b in bad) if bad else "  逸脱なし")

    if args.genlib:
        open(args.genlib, "w").write(genlib(rows))
        print(f"\nwrote {args.genlib}")
